language: php

php:
    - 5.5
    - 5.6
    - 7.1

before_script:
    - wget https://phar.phpunit.de/phpunit-4.8.9.phar
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev

script: php phpunit-4.8.9.phar --coverage-text
